# Generated by Django 2.2.24 on 2021-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0002_auto_20210703_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='latlong',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='distance',
            field=models.CharField(max_length=40),
        ),
    ]
